version: '3.8'

services:
  mysql_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD_DB}
    ports:
      - 3308:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mysql_db
